///// Insert Data to database
db.class.insertMany([
  {
    id: 1,
    Date: "15/10/2024",
    Month: "October",
    Batch: "MERN Stack",
    Topics: "HTML",
    Task: "task1",
    Users: [
      {
        Name: "User1",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User2",
        Attendance: "yes",
        Mentor: "Mentor2",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User3",
        Attendance: "yes",
        Mentor: "Mentor3",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User4",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User5",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "no",
      },
      {
        Name: "User6",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User7",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User8",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User10",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User11",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User12",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User13",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User14",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User15",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User16",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User17",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
    ],
    Mentors: [
      { name: "Mentor1", "Mentee's count": 15 },
      { name: "Mentor2", "Mentee's count": 1 },
      { name: "Mentor3", "Mentee's count": 1 },
    ],
    CompanyDrives: [{ CompanyName: "Cognizant", Attended: ["User1", "User2"] }],
  },
  {
    id: 2,
    Date: "16/10/2024",
    Month: "October",
    Batch: "MERN Stack",
    Topics: "HTML",
    Task: "task2",
    Users: [
      {
        Name: "User1",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User2",
        Attendance: "yes",
        Mentor: "Mentor2",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User3",
        Attendance: "yes",
        Mentor: "Mentor3",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User4",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User5",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "no",
      },
      {
        Name: "User6",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User7",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User8",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User10",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User11",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User12",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User13",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User14",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User15",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User16",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User17",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
    ],
    Mentors: [
      { name: "Mentor1", "Mentee's count": 15 },
      { name: "Mentor2", "Mentee's count": 1 },
      { name: "Mentor3", "Mentee's count": 1 },
    ],
    CompanyDrives: [{ CompanyName: "Tessolve", Attended: ["User1", "User3"] }],
  },
  {
    id: 3,
    Date: "17/10/2024",
    Month: "October",
    Batch: "MERN Stack",
    Topics: "HTML",
    Task: "task3",
    Users: [
      {
        Name: "User1",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User2",
        Attendance: "yes",
        Mentor: "Mentor2",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User3",
        Attendance: "yes",
        Mentor: "Mentor3",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User4",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User5",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "no",
      },
      {
        Name: "User6",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User7",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User8",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User10",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User11",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User12",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User13",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User14",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User15",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User16",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User17",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
    ],
    Mentors: [
      { name: "Mentor1", "Mentee's count": 15 },
      { name: "Mentor2", "Mentee's count": 1 },
      { name: "Mentor3", "Mentee's count": 1 },
    ],
    CompanyDrives: [{ CompanyName: "Accenture", Attended: ["User1"] }],
  },
  {
    id: 4,
    Date: "20/10/2024",
    Month: "October",
    Batch: "MERN Stack",
    Topics: "HTML",
    Task: "task4",
    Users: [
      {
        Name: "User1",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User2",
        Attendance: "yes",
        Mentor: "Mentor2",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User3",
        Attendance: "yes",
        Mentor: "Mentor3",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User4",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User5",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "no",
      },
      {
        Name: "User6",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User7",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User8",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User10",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User11",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User12",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User13",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User14",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User15",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User16",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User17",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
    ],
    Mentors: [
      { name: "Mentor1", "Mentee's count": 15 },
      { name: "Mentor2", "Mentee's count": 1 },
      { name: "Mentor3", "Mentee's count": 1 },
    ],
    CompanyDrives: [{ CompanyName: "Marvel", Attended: ["User1"] }],
  },
  {
    id: 5,
    Date: "30/10/2024",
    Month: "October",
    Batch: "MERN Stack",
    Topics: "HTML",
    Task: "task5",
    Users: [
      {
        Name: "User1",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User2",
        Attendance: "yes",
        Mentor: "Mentor2",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User3",
        Attendance: "yes",
        Mentor: "Mentor3",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User4",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User5",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "no",
      },
      {
        Name: "User6",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User7",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User8",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User9",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User10",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User11",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User12",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User13",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User14",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User15",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User16",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
      {
        Name: "User17",
        Attendance: "yes",
        Mentor: "Mentor1",
        Codekatta: "10",
        TaskCompletion: "yes",
      },
    ],
    Mentors: [
      { name: "Mentor1", "Mentee's count": 15 },
      { name: "Mentor2", "Mentee's count": 1 },
      { name: "Mentor3", "Mentee's count": 1 },
    ],
    CompanyDrives: [{ CompanyName: "Wipro", Attended: ["User1"] }],
  },
]);

////Find the Task and Topics from month of october
db.class.find({ Month: "October" }, { Topics: 1, Task: 1 }).pretty();

///Find all the company drives which appeared between 15 oct-2020 and 31-oct-2020
db.class
  .find(
    { Date: { $gt: ISODate("2020-10-14"), $lt: ISODate("2020-10-31") } },
    { "CompanyDrives.CompanyName": 1 }
  )
  .pretty();

////Find all the company drives and students who are appeared for the placement.
db.class.find({}, { CompanyDrives: 1 }).pretty();

//////Find the number of problems solved by the user in codekata

db.class.aggregate([
  {
    $unwind: "$Users",
  },
  {
    $match: {
      "Users.Name": "User1",
    },
  },
  {
    $group: {
      _id: "$Users.Name",
      totalCodekatta: {
        $sum: { $toInt: "$Users.Codekatta" },
      },
    },
  },
]);
///////////////Find all the mentors with who has the mentee's count more than 15

db.class.aggregate([
  {
    $unwind: "$Mentors",
  },
  {
    $match: {
      "Mentors.MenteeCount": { $gt: 15 },
    },
  },
  {
    $group: {
      _id: "$Mentors.name",
      MaxMenteeCount: { $max: "$Mentors.MenteeCount" },
    },
  },
]);

///////////Find the number of users who are absent and task is not submitted  between 15 oct-2020 and 31-oct-2020

db.class.aggregate([
  {
    $match: {
      Date: { $gte: "15/10/2024", $lte: "31/10/2024" },
    },
  },
  {
    $unwind: "$Users",
  },
  {
    $match: {
      "Users.Attendance": "no",
      "Users.TaskCompletion": "no",
    },
  },
  {
    $group: {
      _id: null,
      totalAbsentNotSubmitted: { $sum: 1 },
    },
  },
  {
    $project: {
      _id: 0,
      totalAbsentNotSubmitted: 1,
    },
  },
]);
